# cloudbuild.yaml
# Builds Docker image, pushes to Container Registry (gcr.io), and deploys to Cloud Run.
# Fixed to avoid any ${SERVICE_URL} template tokens that Cloud Build mistakes for substitutions.

steps:
# 1) Build docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}', '.']

# 2) Push image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}']

# 3) Deploy to Cloud Run using gcloud
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      set -euo pipefail
      echo "Deploying to Cloud Run..."
      gcloud run deploy "${_SERVICE_NAME}" \
        --image="gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}" \
        --region="${_REGION}" \
        --platform=managed \
        --allow-unauthenticated \
        --service-account="consumer-sense-run-sa@${PROJECT_ID}.iam.gserviceaccount.com" \
        --set-env-vars="BQ_TABLE=${_BQ_TABLE},FIRESTORE_COLLECTION=${_FIRESTORE_COLLECTION},VISION_MODEL=${_VISION_MODEL},TEXT_MODEL=${_TEXT_MODEL}" \
        --set-secrets="GEMINI_API_KEY=GEMINI_API_KEY:latest" \
        --concurrency="${_CONCURRENCY}" \
        --memory="${_MEMORY}" \
        --cpu="${_CPU}" \
        --min-instances="${_MIN_INSTANCES}" \
        --max-instances="${_MAX_INSTANCES}" \
        --timeout="${_TIMEOUT_SECS}"

# Optional: Export the deployed Cloud Run URL (do NOT use ${SERVICE_URL} token)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      SERVICE_URL=$(gcloud run services describe "${_SERVICE_NAME}" --region="${_REGION}" --format='value(status.url)')
      # write the runtime SERVICE_URL using plain $SERVICE_URL (no braces) so Cloud Build won't treat it as a template token
      echo "SERVICE_URL=$SERVICE_URL" > /workspace/service_url.txt

images:
- 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}'

# Custom substitutions
substitutions:
  _SERVICE_NAME: "consumer-sense-ai"
  _REGION: "asia-south1"
  _IMAGE_NAME: "consumer-sense-ai"
  _BQ_TABLE: "e-pulsar-478805-s9.consumer_sense_ai.consumer_reviews"
  _FIRESTORE_COLLECTION: "consumer_reviews"
  _VISION_MODEL: "gemini-2.0-flash"
  _TEXT_MODEL: "gemini-2.0-pro"
  _CONCURRENCY: "10"
  _MEMORY: "1Gi"
  _CPU: "1"
  _MIN_INSTANCES: "0"
  _MAX_INSTANCES: "5"
  _TIMEOUT_SECS: "300"

timeout: "1200s"
